import { z } from "zod";
export const MARKET_DATA_ERROR_CODES = {
	SCOPE_DENIED: "MD_SCOPE_DENIED",
	INSTRUMENT_NOT_FOUND: "MD_INSTRUMENT_NOT_FOUND",
	DUPLICATE_OBSERVATION: "MD_DUPLICATE_OBSERVATION",
	REVISION_CONFLICT: "MD_REVISION_CONFLICT",
	EXECUTION_MODE_NOT_SUPPORTED: "MD_EXECUTION_MODE_NOT_SUPPORTED",
	INVALID_QUERY_INPUT: "MD_INVALID_QUERY_INPUT",
	INGEST_BACKPRESSURE: "MD_INGEST_BACKPRESSURE",
	INGEST_SEQUENCE_VIOLATION: "MD_INGEST_SEQUENCE_VIOLATION",
	// ANX-146 slice A (backfill core).
	BACKFILL_JOB_NOT_FOUND: "MD_BACKFILL_JOB_NOT_FOUND",
	BACKFILL_LICENSE_DENIED: "MD_BACKFILL_LICENSE_DENIED",
	BACKFILL_INVALID_TRANSITION: "MD_BACKFILL_INVALID_TRANSITION",
	// ANX-146 slice C (FX + corporate actions, raw vs adjusted, point-in-time).
	INVALID_ADJUSTMENT_FACTOR: "MD_INVALID_ADJUSTMENT_FACTOR",
	// Reserved for a future cross-currency consumer of getAdjustedPrice
	// (this slice's getAdjustedPrice handles same-currency only).
	FX_RATE_NOT_FOUND: "MD_FX_RATE_NOT_FOUND",
};
export const marketDataErrorCodeSchema = z.enum(
	Object.values(MARKET_DATA_ERROR_CODES) as [string, ...string[]],
);
export const MARKET_DATA_ERROR_STATUS_MAP = {
	MD_SCOPE_DENIED: 403,
	MD_INSTRUMENT_NOT_FOUND: 404,
	MD_DUPLICATE_OBSERVATION: 409,
	MD_REVISION_CONFLICT: 409,
	MD_EXECUTION_MODE_NOT_SUPPORTED: 422,
	MD_INVALID_QUERY_INPUT: 422,
	MD_INGEST_BACKPRESSURE: 429,
	MD_INGEST_SEQUENCE_VIOLATION: 422,
	MD_BACKFILL_JOB_NOT_FOUND: 404,
	MD_BACKFILL_LICENSE_DENIED: 403,
	MD_BACKFILL_INVALID_TRANSITION: 409,
	MD_INVALID_ADJUSTMENT_FACTOR: 422,
	MD_FX_RATE_NOT_FOUND: 404,
};
export type MarketDataErrorCode =
	(typeof MARKET_DATA_ERROR_CODES)[keyof typeof MARKET_DATA_ERROR_CODES];
export function resolveMarketDataErrorStatus(
	code: MarketDataErrorCode,
): number {
	return MARKET_DATA_ERROR_STATUS_MAP[
		code as keyof typeof MARKET_DATA_ERROR_STATUS_MAP
	];
}
