import { z } from "zod";
export const MARKET_DATA_ERROR_CODES = {
    SCOPE_DENIED: "MD_SCOPE_DENIED",
    INSTRUMENT_NOT_FOUND: "MD_INSTRUMENT_NOT_FOUND",
    DUPLICATE_OBSERVATION: "MD_DUPLICATE_OBSERVATION",
    REVISION_CONFLICT: "MD_REVISION_CONFLICT",
    EXECUTION_MODE_NOT_SUPPORTED: "MD_EXECUTION_MODE_NOT_SUPPORTED",
};
export const marketDataErrorCodeSchema = z.enum(Object.values(MARKET_DATA_ERROR_CODES) as [string, ...string[]]);
export const MARKET_DATA_ERROR_STATUS_MAP = {
    MD_SCOPE_DENIED: 403,
    MD_INSTRUMENT_NOT_FOUND: 404,
    MD_DUPLICATE_OBSERVATION: 409,
    MD_REVISION_CONFLICT: 409,
    MD_EXECUTION_MODE_NOT_SUPPORTED: 422,
};
export type MarketDataErrorCode = (typeof MARKET_DATA_ERROR_CODES)[keyof typeof MARKET_DATA_ERROR_CODES];
export function resolveMarketDataErrorStatus(code: MarketDataErrorCode): number {
    return MARKET_DATA_ERROR_STATUS_MAP[code as keyof typeof MARKET_DATA_ERROR_STATUS_MAP];
}
