import { z } from "zod";
export const STRATEGIES_ERROR_CODES = {
    SCOPE_DENIED: "ST_SCOPE_DENIED",
    STRATEGY_NOT_FOUND: "ST_STRATEGY_NOT_FOUND",
    VERSION_NOT_FOUND: "ST_VERSION_NOT_FOUND",
    INVALID_LIFECYCLE_TRANSITION: "ST_INVALID_LIFECYCLE_TRANSITION",
    REVISION_CONFLICT: "ST_REVISION_CONFLICT",
    EXECUTION_MODE_NOT_SUPPORTED: "ST_EXECUTION_MODE_NOT_SUPPORTED",
};
export const strategiesErrorCodeSchema = z.enum(Object.values(STRATEGIES_ERROR_CODES) as [string, ...string[]]);
export const STRATEGIES_ERROR_STATUS_MAP = {
    ST_SCOPE_DENIED: 403,
    ST_STRATEGY_NOT_FOUND: 404,
    ST_VERSION_NOT_FOUND: 404,
    ST_INVALID_LIFECYCLE_TRANSITION: 409,
    ST_REVISION_CONFLICT: 409,
    ST_EXECUTION_MODE_NOT_SUPPORTED: 422,
};
export type StrategiesErrorCode = (typeof STRATEGIES_ERROR_CODES)[keyof typeof STRATEGIES_ERROR_CODES];
export function resolveStrategiesErrorStatus(code: StrategiesErrorCode): number {
    return STRATEGIES_ERROR_STATUS_MAP[code as keyof typeof STRATEGIES_ERROR_STATUS_MAP];
}
