import { z } from "zod";
export const STRATEGIES_ERROR_CODES = {
	SCOPE_DENIED: "ST_SCOPE_DENIED",
	CROSS_TENANT: "ST_CROSS_TENANT",
	STRATEGY_NOT_FOUND: "ST_STRATEGY_NOT_FOUND",
	VERSION_NOT_FOUND: "ST_VERSION_NOT_FOUND",
	BACKTEST_NOT_FOUND: "ST_BACKTEST_NOT_FOUND",
	BACKTEST_ALREADY_FINALIZED: "ST_BACKTEST_ALREADY_FINALIZED",
	VERSION_IMMUTABLE: "ST_VERSION_IMMUTABLE",
	INVALID_LIFECYCLE_TRANSITION: "ST_INVALID_LIFECYCLE_TRANSITION",
	REVISION_CONFLICT: "ST_REVISION_CONFLICT",
	EXECUTION_MODE_NOT_SUPPORTED: "ST_EXECUTION_MODE_NOT_SUPPORTED",
	DEPLOYMENT_NOT_FOUND: "ST_DEPLOYMENT_NOT_FOUND",
	SIGNAL_EXPIRED: "ST_SIGNAL_EXPIRED",
	BINDING_IMMUTABLE: "ST_BINDING_IMMUTABLE",
	CERTIFICATION_REQUIRED: "ST_CERTIFICATION_REQUIRED",
};
export const strategiesErrorCodeSchema = z.enum(
	Object.values(STRATEGIES_ERROR_CODES) as [string, ...string[]],
);
export const STRATEGIES_ERROR_STATUS_MAP = {
	ST_SCOPE_DENIED: 403,
	ST_CROSS_TENANT: 403,
	ST_STRATEGY_NOT_FOUND: 404,
	ST_VERSION_NOT_FOUND: 404,
	ST_BACKTEST_NOT_FOUND: 404,
	ST_BACKTEST_ALREADY_FINALIZED: 409,
	ST_VERSION_IMMUTABLE: 409,
	ST_INVALID_LIFECYCLE_TRANSITION: 409,
	ST_REVISION_CONFLICT: 409,
	ST_EXECUTION_MODE_NOT_SUPPORTED: 422,
	ST_DEPLOYMENT_NOT_FOUND: 404,
	ST_SIGNAL_EXPIRED: 422,
	ST_BINDING_IMMUTABLE: 409,
	ST_CERTIFICATION_REQUIRED: 409,
};
export type StrategiesErrorCode =
	(typeof STRATEGIES_ERROR_CODES)[keyof typeof STRATEGIES_ERROR_CODES];
export function resolveStrategiesErrorStatus(
	code: StrategiesErrorCode,
): number {
	return STRATEGIES_ERROR_STATUS_MAP[
		code as keyof typeof STRATEGIES_ERROR_STATUS_MAP
	];
}
