import type { EdgeTypeDef } from "./edge-types";
import type { NodeTypeDef } from "./node-types";

/** Agent Graph node types — ownerDomain `agents` (ADR0005 P3 proposed). */
export const AGENT_GRAPH_NODE_TYPES: readonly NodeTypeDef[] = [
	{
		nodeType: "Agent",
		schemaVersion: 1,
		ownerDomain: "agents",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/agents/Agent.json",
		checksum: "sha256:agents-agent-v1",
	},
	{
		nodeType: "AgentRoleTaxonomy",
		schemaVersion: 1,
		ownerDomain: "agents",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/agents/AgentRoleTaxonomy.json",
		checksum: "sha256:agents-agent-role-taxonomy-v1",
	},
	{
		nodeType: "Department",
		schemaVersion: 1,
		ownerDomain: "agents",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/agents/Department.json",
		checksum: "sha256:agents-department-v1",
	},
	{
		nodeType: "AgentTeam",
		schemaVersion: 1,
		ownerDomain: "agents",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/agents/AgentTeam.json",
		checksum: "sha256:agents-agent-team-v1",
	},
	{
		nodeType: "AgentCapability",
		schemaVersion: 1,
		ownerDomain: "agents",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/agents/AgentCapability.json",
		checksum: "sha256:agents-agent-capability-v1",
	},
	{
		nodeType: "Objective",
		schemaVersion: 1,
		ownerDomain: "agents",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/agents/Objective.json",
		checksum: "sha256:agents-objective-v1",
	},
	{
		nodeType: "KnowledgeRef",
		schemaVersion: 1,
		ownerDomain: "agents",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/agents/KnowledgeRef.json",
		checksum: "sha256:agents-knowledge-ref-v1",
	},
	{
		nodeType: "PerformanceSnapshot",
		schemaVersion: 1,
		ownerDomain: "agents",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/agents/PerformanceSnapshot.json",
		checksum: "sha256:agents-performance-snapshot-v1",
	},
	{
		nodeType: "Decision",
		schemaVersion: 1,
		ownerDomain: "agents",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/agents/Decision.json",
		checksum: "sha256:agents-decision-v1",
	},
];

/** Agent Graph edge types — organizational + capability relations. */
export const AGENT_GRAPH_EDGE_TYPES: readonly EdgeTypeDef[] = [
	{
		edgeTypeId: "agents.belongs_to",
		edgeType: "BELONGS_TO",
		schemaVersion: 1,
		fromNodeTypes: ["Agent"],
		toNodeTypes: ["Department"],
		writerDomain: "agents",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "agents.reports_to",
		edgeType: "REPORTS_TO",
		schemaVersion: 1,
		fromNodeTypes: ["Agent"],
		toNodeTypes: ["Agent"],
		writerDomain: "agents",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "agents.manages",
		edgeType: "MANAGES",
		schemaVersion: 1,
		fromNodeTypes: ["Agent"],
		toNodeTypes: ["Agent"],
		writerDomain: "agents",
		cardinality: "one-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "agents.paired_with",
		edgeType: "PAIRED_WITH",
		schemaVersion: 1,
		fromNodeTypes: ["Agent"],
		toNodeTypes: ["Agent"],
		writerDomain: "agents",
		cardinality: "one-to-one",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "agents.can_execute",
		edgeType: "CAN_EXECUTE",
		schemaVersion: 1,
		fromNodeTypes: ["Agent"],
		toNodeTypes: ["AgentCapability"],
		writerDomain: "agents",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "agents.knows",
		edgeType: "KNOWS",
		schemaVersion: 1,
		fromNodeTypes: ["Agent"],
		toNodeTypes: ["KnowledgeRef"],
		writerDomain: "agents",
		cardinality: "many-to-many",
		temporal: false,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "agents.member_of",
		edgeType: "MEMBER_OF",
		schemaVersion: 1,
		fromNodeTypes: ["Agent"],
		toNodeTypes: ["AgentTeam"],
		writerDomain: "agents",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "agents.leads",
		edgeType: "LEADS",
		schemaVersion: 1,
		fromNodeTypes: ["Agent"],
		toNodeTypes: ["AgentTeam"],
		writerDomain: "agents",
		cardinality: "one-to-one",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "agents.responsible_for",
		edgeType: "RESPONSIBLE_FOR",
		schemaVersion: 1,
		fromNodeTypes: ["Agent", "AgentTeam"],
		toNodeTypes: ["Objective"],
		writerDomain: "agents",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "agents.created",
		edgeType: "CREATED",
		schemaVersion: 1,
		fromNodeTypes: ["Agent"],
		toNodeTypes: ["CodeArtifact", "ResearchArtifact"],
		writerDomain: "agents",
		cardinality: "one-to-many",
		temporal: false,
		crossScopePolicy: "cross-scope-allowed",
		status: "active",
	},
	{
		edgeTypeId: "agents.approved",
		edgeType: "APPROVED",
		schemaVersion: 1,
		fromNodeTypes: ["Agent"],
		toNodeTypes: ["Decision"],
		writerDomain: "agents",
		cardinality: "many-to-many",
		temporal: false,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "agents.covers_role",
		edgeType: "COVERS_ROLE",
		schemaVersion: 1,
		fromNodeTypes: ["Agent"],
		toNodeTypes: ["AgentRoleTaxonomy"],
		writerDomain: "agents",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "agents.communicates_with",
		edgeType: "COMMUNICATES_WITH",
		schemaVersion: 1,
		fromNodeTypes: ["Agent"],
		toNodeTypes: ["Agent"],
		writerDomain: "agents",
		cardinality: "many-to-many",
		temporal: false,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "agents.depends_on",
		edgeType: "DEPENDS_ON",
		schemaVersion: 1,
		fromNodeTypes: ["Agent"],
		toNodeTypes: ["Agent"],
		writerDomain: "agents",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "agents.bridges_product_role",
		edgeType: "BRIDGES_PRODUCT_ROLE",
		schemaVersion: 1,
		fromNodeTypes: ["AgentRoleTaxonomy"],
		toNodeTypes: ["AgentRole"],
		writerDomain: "agents",
		cardinality: "one-to-one",
		temporal: false,
		crossScopePolicy: "cross-scope-allowed",
		status: "active",
	},
];
