import type { EdgeTypeDef } from "./edge-types";
import type { NodeTypeDef } from "./node-types";

/** Domain traversal node types (T06-T20) — P03 S5 ANX-305 / R03-schema-registry. */
export const GRAPH_DOMAIN_TRAVERSAL_NODE_TYPES = [
	{
		nodeType: "Goal",
		schemaVersion: 1,
		ownerDomain: "agents",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/agents/Goal.json",
		checksum: "sha256:domain-goal-v1",
	},
	{
		nodeType: "Task",
		schemaVersion: 1,
		ownerDomain: "agents",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/agents/Task.json",
		checksum: "sha256:domain-task-v1",
	},
	{
		nodeType: "Agent",
		schemaVersion: 1,
		ownerDomain: "agents",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/agents/Agent.json",
		checksum: "sha256:domain-agent-v1",
	},
	{
		nodeType: "Portfolio",
		schemaVersion: 1,
		ownerDomain: "portfolios",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/portfolios/Portfolio.json",
		checksum: "sha256:domain-portfolio-v1",
	},
	{
		nodeType: "CapitalAccount",
		schemaVersion: 1,
		ownerDomain: "capital",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/capital/CapitalAccount.json",
		checksum: "sha256:domain-capital-account-v1",
	},
	{
		nodeType: "Position",
		schemaVersion: 1,
		ownerDomain: "portfolios",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/portfolios/Position.json",
		checksum: "sha256:domain-position-v1",
	},
	{
		nodeType: "Instrument",
		schemaVersion: 1,
		ownerDomain: "market-data",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/market-data/Instrument.json",
		checksum: "sha256:domain-instrument-v1",
	},
	{
		nodeType: "Asset",
		schemaVersion: 1,
		ownerDomain: "market-data",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/market-data/Asset.json",
		checksum: "sha256:domain-asset-v1",
	},
	{
		nodeType: "Strategy",
		schemaVersion: 1,
		ownerDomain: "strategies",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/strategies/Strategy.json",
		checksum: "sha256:domain-strategy-v1",
	},
	{
		nodeType: "StrategyVersion",
		schemaVersion: 1,
		ownerDomain: "strategies",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/strategies/StrategyVersion.json",
		checksum: "sha256:domain-strategy-version-v1",
	},
	{
		nodeType: "Deployment",
		schemaVersion: 1,
		ownerDomain: "strategies",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/strategies/Deployment.json",
		checksum: "sha256:domain-deployment-v1",
	},
	{
		nodeType: "Order",
		schemaVersion: 1,
		ownerDomain: "execution",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/execution/Order.json",
		checksum: "sha256:domain-order-v1",
	},
	{
		nodeType: "Fill",
		schemaVersion: 1,
		ownerDomain: "execution",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/execution/Fill.json",
		checksum: "sha256:domain-fill-v1",
	},
	{
		nodeType: "TradeIntent",
		schemaVersion: 1,
		ownerDomain: "decisions",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/decisions/TradeIntent.json",
		checksum: "sha256:domain-trade-intent-v1",
	},
	{
		nodeType: "Approval",
		schemaVersion: 1,
		ownerDomain: "governance",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/governance/Approval.json",
		checksum: "sha256:domain-approval-v1",
	},
	{
		nodeType: "Decision",
		schemaVersion: 1,
		ownerDomain: "decisions",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/decisions/Decision.json",
		checksum: "sha256:domain-decision-v1",
	},
	{
		nodeType: "Evidence",
		schemaVersion: 1,
		ownerDomain: "knowledge",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/knowledge/Evidence.json",
		checksum: "sha256:domain-evidence-v1",
	},
	{
		nodeType: "ContextManifest",
		schemaVersion: 1,
		ownerDomain: "knowledge",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/knowledge/ContextManifest.json",
		checksum: "sha256:domain-context-manifest-v1",
	},
	{
		nodeType: "RoutingDecision",
		schemaVersion: 1,
		ownerDomain: "connections",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/connections/RoutingDecision.json",
		checksum: "sha256:domain-routing-decision-v1",
	},
	{
		nodeType: "InferenceAttempt",
		schemaVersion: 1,
		ownerDomain: "connections",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/connections/InferenceAttempt.json",
		checksum: "sha256:domain-inference-attempt-v1",
	},
	{
		nodeType: "OfferingAccessGrant",
		schemaVersion: 1,
		ownerDomain: "connections",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/connections/OfferingAccessGrant.json",
		checksum: "sha256:domain-offering-access-grant-v1",
	},
	{
		nodeType: "ReconciliationCase",
		schemaVersion: 1,
		ownerDomain: "execution",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/execution/ReconciliationCase.json",
		checksum: "sha256:domain-reconciliation-case-v1",
	},
	{
		nodeType: "LedgerEntry",
		schemaVersion: 1,
		ownerDomain: "accounting",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/accounting/LedgerEntry.json",
		checksum: "sha256:domain-ledger-entry-v1",
	},
	{
		nodeType: "UsageRecord",
		schemaVersion: 1,
		ownerDomain: "billing",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/billing/UsageRecord.json",
		checksum: "sha256:domain-usage-record-v1",
	},
	{
		nodeType: "GraphSnapshot",
		schemaVersion: 1,
		ownerDomain: "evaluation",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/evaluation/GraphSnapshot.json",
		checksum: "sha256:domain-graph-snapshot-v1",
	},
	{
		nodeType: "ChangeProposal",
		schemaVersion: 1,
		ownerDomain: "evaluation",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/evaluation/ChangeProposal.json",
		checksum: "sha256:domain-change-proposal-v1",
	},
	{
		nodeType: "AuthorityGrant",
		schemaVersion: 1,
		ownerDomain: "governance",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/governance/AuthorityGrant.json",
		checksum: "sha256:domain-authority-grant-v1",
	},
	{
		nodeType: "Referral",
		schemaVersion: 1,
		ownerDomain: "partners",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/partners/Referral.json",
		checksum: "sha256:domain-referral-v1",
	},
	{
		nodeType: "Commission",
		schemaVersion: 1,
		ownerDomain: "partners",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/partners/Commission.json",
		checksum: "sha256:domain-commission-v1",
	},
	{
		nodeType: "Invoice",
		schemaVersion: 1,
		ownerDomain: "billing",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/billing/Invoice.json",
		checksum: "sha256:domain-invoice-v1",
	},
] satisfies readonly NodeTypeDef[];

export const GRAPH_DOMAIN_TRAVERSAL_EDGE_TYPES = [
	{
		edgeTypeId: "agents.has_subgoal",
		edgeType: "HAS_SUBGOAL",
		schemaVersion: 1,
		fromNodeTypes: ["Goal"],
		toNodeTypes: ["Goal", "Task"],
		writerDomain: "agents",
		cardinality: "one-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "agents.advances_goal",
		edgeType: "ADVANCES_GOAL",
		schemaVersion: 1,
		fromNodeTypes: ["Task"],
		toNodeTypes: ["Goal"],
		writerDomain: "agents",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "agents.depends_on_task",
		edgeType: "DEPENDS_ON_TASK",
		schemaVersion: 1,
		fromNodeTypes: ["Goal", "Task"],
		toNodeTypes: ["Task"],
		writerDomain: "agents",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "agents.assigned_to",
		edgeType: "ASSIGNED_TO",
		schemaVersion: 1,
		fromNodeTypes: ["Task"],
		toNodeTypes: ["Agent"],
		writerDomain: "agents",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "agents.pursues_goal",
		edgeType: "PURSUES_GOAL",
		schemaVersion: 1,
		fromNodeTypes: ["Agent", "Task"],
		toNodeTypes: ["Goal"],
		writerDomain: "agents",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "agents.executed_by_agent",
		edgeType: "EXECUTED_BY_AGENT",
		schemaVersion: 1,
		fromNodeTypes: ["Deployment", "Strategy"],
		toNodeTypes: ["Agent"],
		writerDomain: "agents",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "portfolios.managed_by",
		edgeType: "MANAGED_BY",
		schemaVersion: 1,
		fromNodeTypes: ["Portfolio"],
		toNodeTypes: ["Agent"],
		writerDomain: "portfolios",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "portfolios.from_capital_account",
		edgeType: "FROM_CAPITAL_ACCOUNT",
		schemaVersion: 1,
		fromNodeTypes: ["Portfolio"],
		toNodeTypes: ["CapitalAccount"],
		writerDomain: "portfolios",
		cardinality: "one-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "portfolios.has_deployment",
		edgeType: "HAS_DEPLOYMENT",
		schemaVersion: 1,
		fromNodeTypes: ["Portfolio", "Strategy", "StrategyVersion"],
		toNodeTypes: ["Deployment"],
		writerDomain: "portfolios",
		cardinality: "one-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "strategies.uses_strategy_version",
		edgeType: "USES_STRATEGY_VERSION",
		schemaVersion: 1,
		fromNodeTypes: ["Deployment", "Strategy", "Decision"],
		toNodeTypes: ["StrategyVersion"],
		writerDomain: "strategies",
		cardinality: "many-to-one",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "market-data.on_instrument",
		edgeType: "ON_INSTRUMENT",
		schemaVersion: 1,
		fromNodeTypes: ["Position"],
		toNodeTypes: ["Instrument"],
		writerDomain: "market-data",
		cardinality: "many-to-one",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "market-data.represents_asset",
		edgeType: "REPRESENTS_ASSET",
		schemaVersion: 1,
		fromNodeTypes: ["Instrument"],
		toNodeTypes: ["Asset"],
		writerDomain: "market-data",
		cardinality: "many-to-one",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "decisions.made_by",
		edgeType: "MADE_BY",
		schemaVersion: 1,
		fromNodeTypes: ["Decision"],
		toNodeTypes: ["Agent"],
		writerDomain: "decisions",
		cardinality: "many-to-one",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "knowledge.based_on",
		edgeType: "BASED_ON",
		schemaVersion: 1,
		fromNodeTypes: ["Decision"],
		toNodeTypes: ["Evidence"],
		writerDomain: "knowledge",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "knowledge.uses_context",
		edgeType: "USES_CONTEXT",
		schemaVersion: 1,
		fromNodeTypes: ["Decision"],
		toNodeTypes: ["ContextManifest"],
		writerDomain: "knowledge",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "connections.uses_inference",
		edgeType: "USES_INFERENCE",
		schemaVersion: 1,
		fromNodeTypes: ["Decision"],
		toNodeTypes: ["InferenceRequest"],
		writerDomain: "connections",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "execution.filled_as",
		edgeType: "FILLED_AS",
		schemaVersion: 1,
		fromNodeTypes: ["Fill"],
		toNodeTypes: ["Order"],
		writerDomain: "execution",
		cardinality: "many-to-one",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "execution.materializes_order",
		edgeType: "MATERIALIZES_ORDER",
		schemaVersion: 1,
		fromNodeTypes: ["TradeIntent"],
		toNodeTypes: ["Order"],
		writerDomain: "execution",
		cardinality: "one-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "governance.checked_by",
		edgeType: "CHECKED_BY",
		schemaVersion: 1,
		fromNodeTypes: ["Order", "Fill"],
		toNodeTypes: ["Approval"],
		writerDomain: "governance",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "decisions.for_intent",
		edgeType: "FOR_INTENT",
		schemaVersion: 1,
		fromNodeTypes: ["Order"],
		toNodeTypes: ["TradeIntent"],
		writerDomain: "decisions",
		cardinality: "many-to-one",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "decisions.proposes_intent",
		edgeType: "PROPOSES_INTENT",
		schemaVersion: 1,
		fromNodeTypes: ["Agent"],
		toNodeTypes: ["TradeIntent"],
		writerDomain: "decisions",
		cardinality: "one-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "connections.selects_model",
		edgeType: "SELECTS_MODEL",
		schemaVersion: 1,
		fromNodeTypes: ["AgentModelBinding"],
		toNodeTypes: ["ModelOffering"],
		writerDomain: "connections",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "connections.permits_offering",
		edgeType: "PERMITS_OFFERING",
		schemaVersion: 1,
		fromNodeTypes: ["OfferingAccessGrant"],
		toNodeTypes: ["ModelOffering"],
		writerDomain: "connections",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "cross-scope-allowed",
		status: "active",
	},
	{
		edgeTypeId: "connections.has_inference_attempt",
		edgeType: "HAS_INFERENCE_ATTEMPT",
		schemaVersion: 1,
		fromNodeTypes: ["RoutingDecision", "InferenceRequest"],
		toNodeTypes: ["InferenceAttempt"],
		writerDomain: "connections",
		cardinality: "one-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "connections.attempted_via",
		edgeType: "ATTEMPTED_VIA",
		schemaVersion: 1,
		fromNodeTypes: ["InferenceAttempt"],
		toNodeTypes: ["Connection"],
		writerDomain: "connections",
		cardinality: "many-to-one",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "billing.generated_usage",
		edgeType: "GENERATED_USAGE",
		schemaVersion: 1,
		fromNodeTypes: ["UsageRecord"],
		toNodeTypes: ["Agent", "Task", "InferenceAttempt"],
		writerDomain: "billing",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "billing.charged_to",
		edgeType: "CHARGED_TO",
		schemaVersion: 1,
		fromNodeTypes: ["UsageRecord"],
		toNodeTypes: ["Agent", "CapitalAccount"],
		writerDomain: "billing",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "execution.reconciles_resource",
		edgeType: "RECONCILES_RESOURCE",
		schemaVersion: 1,
		fromNodeTypes: ["ReconciliationCase"],
		toNodeTypes: ["Order", "Fill", "Portfolio"],
		writerDomain: "execution",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "accounting.posts_ledger",
		edgeType: "POSTS_LEDGER",
		schemaVersion: 1,
		fromNodeTypes: ["ReconciliationCase", "Order", "Fill"],
		toNodeTypes: ["LedgerEntry"],
		writerDomain: "accounting",
		cardinality: "one-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "evaluation.uses_snapshot",
		edgeType: "USES_SNAPSHOT",
		schemaVersion: 1,
		fromNodeTypes: ["ChangeProposal"],
		toNodeTypes: ["GraphSnapshot"],
		writerDomain: "evaluation",
		cardinality: "many-to-one",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "evaluation.tests_change",
		edgeType: "TESTS_CHANGE",
		schemaVersion: 1,
		fromNodeTypes: ["ChangeProposal"],
		toNodeTypes: ["AuthorityGrant", "Approval"],
		writerDomain: "evaluation",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "evaluation.changes_resource",
		edgeType: "CHANGES_RESOURCE",
		schemaVersion: 1,
		fromNodeTypes: ["ChangeProposal"],
		toNodeTypes: ["AuthorityGrant", "Portfolio", "Deployment"],
		writerDomain: "evaluation",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "partners.attributed_to",
		edgeType: "ATTRIBUTED_TO",
		schemaVersion: 1,
		fromNodeTypes: ["Commission"],
		toNodeTypes: ["Referral"],
		writerDomain: "partners",
		cardinality: "many-to-one",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "partners.earned_from",
		edgeType: "EARNED_FROM",
		schemaVersion: 1,
		fromNodeTypes: ["Commission"],
		toNodeTypes: ["Invoice"],
		writerDomain: "partners",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "partners.settles_commission",
		edgeType: "SETTLES_COMMISSION",
		schemaVersion: 1,
		fromNodeTypes: ["Commission"],
		toNodeTypes: ["Invoice"],
		writerDomain: "partners",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
] satisfies readonly EdgeTypeDef[];
