import type { EdgeTypeDef } from "./edge-types";
import type { NodeTypeDef } from "./node-types";

/** Kernel node types for T12/T14 traversals (P03 ANX-303). */
export const GRAPH_KERNEL_NODE_TYPES = [
	{
		nodeType: "Outcome",
		schemaVersion: 1,
		ownerDomain: "performance",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/Outcome.json",
		checksum: "sha256:kernel-outcome-v1",
	},
	{
		nodeType: "PerformanceAttribution",
		schemaVersion: 1,
		ownerDomain: "performance",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/PerformanceAttribution.json",
		checksum: "sha256:kernel-performance-attribution-v1",
	},
	{
		nodeType: "Fill",
		schemaVersion: 1,
		ownerDomain: "execution",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/Fill.json",
		checksum: "sha256:kernel-fill-v1",
	},
	{
		nodeType: "Connection",
		schemaVersion: 1,
		ownerDomain: "connections",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/Connection.json",
		checksum: "sha256:kernel-connection-v1",
	},
	{
		nodeType: "ModelOffering",
		schemaVersion: 1,
		ownerDomain: "connections",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/ModelOffering.json",
		checksum: "sha256:kernel-model-offering-v1",
	},
	{
		nodeType: "AgentModelBinding",
		schemaVersion: 1,
		ownerDomain: "connections",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/AgentModelBinding.json",
		checksum: "sha256:kernel-agent-model-binding-v1",
	},
	{
		nodeType: "InferenceRequest",
		schemaVersion: 1,
		ownerDomain: "connections",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/InferenceRequest.json",
		checksum: "sha256:kernel-inference-request-v1",
	},
] satisfies readonly NodeTypeDef[];

export const GRAPH_KERNEL_EDGE_TYPES = [
	{
		edgeTypeId: "performance.attributes_outcome",
		edgeType: "ATTRIBUTES_OUTCOME",
		schemaVersion: 1,
		fromNodeTypes: ["PerformanceAttribution"],
		toNodeTypes: ["Outcome"],
		writerDomain: "performance",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "performance.contribution_from",
		edgeType: "CONTRIBUTION_FROM",
		schemaVersion: 1,
		fromNodeTypes: ["Fill"],
		toNodeTypes: ["PerformanceAttribution"],
		writerDomain: "performance",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "connections.served_via",
		edgeType: "SERVED_VIA",
		schemaVersion: 1,
		fromNodeTypes: ["ModelOffering"],
		toNodeTypes: ["Connection"],
		writerDomain: "connections",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "connections.has_model_binding",
		edgeType: "HAS_MODEL_BINDING",
		schemaVersion: 1,
		fromNodeTypes: ["ModelOffering", "AgentModelBinding"],
		toNodeTypes: ["AgentModelBinding", "Connection"],
		writerDomain: "connections",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "connections.has_routing_decision",
		edgeType: "HAS_ROUTING_DECISION",
		schemaVersion: 1,
		fromNodeTypes: ["InferenceRequest"],
		toNodeTypes: ["AgentModelBinding"],
		writerDomain: "connections",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
] satisfies readonly EdgeTypeDef[];
