import type { EdgeTypeDef } from "./edge-types";
import type { NodeTypeDef } from "./node-types";

/** Product Graph node types — ownerDomain `product` (ADR0005 P3 proposed). */
export const PRODUCT_GRAPH_NODE_TYPES: readonly NodeTypeDef[] = [
	{
		nodeType: "Company",
		schemaVersion: 1,
		ownerDomain: "product",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/product/Company.json",
		checksum: "sha256:product-company-v1",
	},
	{
		nodeType: "Product",
		schemaVersion: 1,
		ownerDomain: "product",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/product/Product.json",
		checksum: "sha256:product-product-v1",
	},
	{
		nodeType: "Problem",
		schemaVersion: 1,
		ownerDomain: "product",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/product/Problem.json",
		checksum: "sha256:product-problem-v1",
	},
	{
		nodeType: "UserPersona",
		schemaVersion: 1,
		ownerDomain: "product",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/product/UserPersona.json",
		checksum: "sha256:product-user-persona-v1",
	},
	{
		nodeType: "Requirement",
		schemaVersion: 1,
		ownerDomain: "product",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/product/Requirement.json",
		checksum: "sha256:product-requirement-v1",
	},
	{
		nodeType: "Feature",
		schemaVersion: 1,
		ownerDomain: "product",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/product/Feature.json",
		checksum: "sha256:product-feature-v1",
	},
	{
		nodeType: "Capability",
		schemaVersion: 1,
		ownerDomain: "product",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/product/Capability.json",
		checksum: "sha256:product-capability-v1",
	},
	{
		nodeType: "Service",
		schemaVersion: 1,
		ownerDomain: "product",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/product/Service.json",
		checksum: "sha256:product-service-v1",
	},
	{
		nodeType: "CodeArtifact",
		schemaVersion: 1,
		ownerDomain: "product",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/product/CodeArtifact.json",
		checksum: "sha256:product-code-artifact-v1",
	},
	{
		nodeType: "TestArtifact",
		schemaVersion: 1,
		ownerDomain: "product",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/product/TestArtifact.json",
		checksum: "sha256:product-test-artifact-v1",
	},
	{
		nodeType: "Deployment",
		schemaVersion: 1,
		ownerDomain: "product",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/product/Deployment.json",
		checksum: "sha256:product-deployment-v1",
	},
	{
		nodeType: "Monitor",
		schemaVersion: 1,
		ownerDomain: "product",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/product/Monitor.json",
		checksum: "sha256:product-monitor-v1",
	},
	{
		nodeType: "WorkItem",
		schemaVersion: 1,
		ownerDomain: "product",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/product/WorkItem.json",
		checksum: "sha256:product-work-item-v1",
	},
	{
		nodeType: "AgentRole",
		schemaVersion: 1,
		ownerDomain: "product",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/product/AgentRole.json",
		checksum: "sha256:product-agent-role-v1",
	},
	{
		nodeType: "ResearchArtifact",
		schemaVersion: 1,
		ownerDomain: "product",
		status: "active",
		payloadSchemaRef: "graph/schema/v1/product/ResearchArtifact.json",
		checksum: "sha256:product-research-artifact-v1",
	},
];

/** Product Graph edge types — reconstructible projection (ADR0005). */
export const PRODUCT_GRAPH_EDGE_TYPES: readonly EdgeTypeDef[] = [
	{
		edgeTypeId: "product.owns",
		edgeType: "OWNS",
		schemaVersion: 1,
		fromNodeTypes: ["Company"],
		toNodeTypes: ["Product"],
		writerDomain: "product",
		cardinality: "one-to-many",
		temporal: false,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "product.targets",
		edgeType: "TARGETS",
		schemaVersion: 1,
		fromNodeTypes: ["Product"],
		toNodeTypes: ["UserPersona"],
		writerDomain: "product",
		cardinality: "many-to-many",
		temporal: false,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "product.addresses",
		edgeType: "ADDRESSES",
		schemaVersion: 1,
		fromNodeTypes: ["Feature", "Requirement"],
		toNodeTypes: ["Problem"],
		writerDomain: "product",
		cardinality: "many-to-many",
		temporal: false,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "product.derives_from",
		edgeType: "DERIVES_FROM",
		schemaVersion: 1,
		fromNodeTypes: ["Requirement"],
		toNodeTypes: ["ResearchArtifact", "Problem"],
		writerDomain: "product",
		cardinality: "many-to-many",
		temporal: false,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "product.refines",
		edgeType: "REFINES",
		schemaVersion: 1,
		fromNodeTypes: ["Requirement"],
		toNodeTypes: ["Requirement"],
		writerDomain: "product",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "product.implements",
		edgeType: "IMPLEMENTS",
		schemaVersion: 1,
		fromNodeTypes: ["Feature"],
		toNodeTypes: ["Requirement"],
		writerDomain: "product",
		cardinality: "many-to-many",
		temporal: false,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "product.enables",
		edgeType: "ENABLES",
		schemaVersion: 1,
		fromNodeTypes: ["Capability"],
		toNodeTypes: ["Feature"],
		writerDomain: "product",
		cardinality: "one-to-many",
		temporal: false,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "product.realized_by",
		edgeType: "REALIZED_BY",
		schemaVersion: 1,
		fromNodeTypes: ["Feature"],
		toNodeTypes: ["Service"],
		writerDomain: "product",
		cardinality: "many-to-many",
		temporal: false,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "product.contains_code",
		edgeType: "CONTAINS_CODE",
		schemaVersion: 1,
		fromNodeTypes: ["Service"],
		toNodeTypes: ["CodeArtifact"],
		writerDomain: "product",
		cardinality: "one-to-many",
		temporal: false,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "product.verified_by",
		edgeType: "VERIFIED_BY",
		schemaVersion: 1,
		fromNodeTypes: ["CodeArtifact", "Feature"],
		toNodeTypes: ["TestArtifact"],
		writerDomain: "product",
		cardinality: "many-to-many",
		temporal: false,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "product.deployed_to",
		edgeType: "DEPLOYED_TO",
		schemaVersion: 1,
		fromNodeTypes: ["Service", "Feature"],
		toNodeTypes: ["Deployment"],
		writerDomain: "product",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "product.monitored_by",
		edgeType: "MONITORED_BY",
		schemaVersion: 1,
		fromNodeTypes: ["Deployment", "Service"],
		toNodeTypes: ["Monitor"],
		writerDomain: "product",
		cardinality: "one-to-many",
		temporal: false,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "product.tracked_in",
		edgeType: "TRACKED_IN",
		schemaVersion: 1,
		fromNodeTypes: ["Feature", "Requirement"],
		toNodeTypes: ["WorkItem"],
		writerDomain: "product",
		cardinality: "many-to-many",
		temporal: false,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "product.owned_by_agent",
		edgeType: "OWNED_BY_AGENT",
		schemaVersion: 1,
		fromNodeTypes: ["WorkItem", "Feature"],
		toNodeTypes: ["AgentRole"],
		writerDomain: "product",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "cross-scope-allowed",
		status: "active",
	},
	{
		edgeTypeId: "product.depends_on",
		edgeType: "DEPENDS_ON",
		schemaVersion: 1,
		fromNodeTypes: ["Service", "Feature", "CodeArtifact"],
		toNodeTypes: ["Service", "Feature", "CodeArtifact"],
		writerDomain: "product",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "product.feeds_back",
		edgeType: "FEEDS_BACK",
		schemaVersion: 1,
		fromNodeTypes: ["Monitor"],
		toNodeTypes: ["Problem", "ResearchArtifact"],
		writerDomain: "product",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
	{
		edgeTypeId: "product.assigned_to",
		edgeType: "ASSIGNED_TO",
		schemaVersion: 1,
		fromNodeTypes: ["AgentRole"],
		toNodeTypes: ["WorkItem"],
		writerDomain: "product",
		cardinality: "many-to-many",
		temporal: true,
		crossScopePolicy: "same-scope",
		status: "active",
	},
];
