import { z } from "zod";
export const KNOWLEDGE_ERROR_CODES = {
    SCOPE_DENIED: "KN_SCOPE_DENIED",
    IDEMPOTENT_REPLAY: "KN_IDEMPOTENT_REPLAY",
    SOURCE_NOT_FOUND: "KN_SOURCE_NOT_FOUND",
    DOCUMENT_NOT_FOUND: "KN_DOCUMENT_NOT_FOUND",
    INDEX_NOT_FOUND: "KN_INDEX_NOT_FOUND",
    INDEX_NOT_READY: "KN_INDEX_NOT_READY",
    REVISION_CONFLICT: "KN_REVISION_CONFLICT",
    INSUFFICIENT_EVIDENCE: "KN_INSUFFICIENT_EVIDENCE",
    CROSS_TENANT: "KN_CROSS_TENANT",
};
export const knowledgeErrorCodeSchema = z.enum(Object.values(KNOWLEDGE_ERROR_CODES) as [string, ...string[]]);
export const KNOWLEDGE_ERROR_STATUS_MAP = {
    KN_SCOPE_DENIED: 403,
    KN_IDEMPOTENT_REPLAY: 200,
    KN_SOURCE_NOT_FOUND: 404,
    KN_DOCUMENT_NOT_FOUND: 404,
    KN_INDEX_NOT_FOUND: 404,
    KN_INDEX_NOT_READY: 409,
    KN_REVISION_CONFLICT: 409,
    KN_INSUFFICIENT_EVIDENCE: 422,
    KN_CROSS_TENANT: 403,
};
export type KnowledgeErrorCode = (typeof KNOWLEDGE_ERROR_CODES)[keyof typeof KNOWLEDGE_ERROR_CODES];
export function resolveKnowledgeErrorStatus(code: KnowledgeErrorCode): number {
    return KNOWLEDGE_ERROR_STATUS_MAP[code as keyof typeof KNOWLEDGE_ERROR_STATUS_MAP];
}
