import { z } from "zod";
export const OPERATIONS_ERROR_CODES = {
	DUPLICATE_IDEMPOTENCY: "OPS_DUPLICATE_IDEMPOTENCY",
	CROSS_TENANT: "OPS_CROSS_TENANT",
	GRANT_INVALID: "OPS_GRANT_INVALID",
	INCIDENT_NOT_FOUND: "OPS_INCIDENT_NOT_FOUND",
	INCIDENT_STATUS_INVALID: "OPS_INCIDENT_STATUS_INVALID",
	INCIDENT_RUNBOOK_REQUIRED: "OPS_INCIDENT_RUNBOOK_REQUIRED",
	HEALTH_CHECK_NOT_FOUND: "OPS_HEALTH_CHECK_NOT_FOUND",
	STALE_CHECKED_AT: "OPS_STALE_CHECKED_AT",
	REVISION_CONFLICT: "OPS_REVISION_CONFLICT",
};
export const operationsErrorCodeSchema = z.enum(
	Object.values(OPERATIONS_ERROR_CODES) as [string, ...string[]],
);
export const OPERATIONS_ERROR_STATUS_MAP = {
	OPS_DUPLICATE_IDEMPOTENCY: 409,
	OPS_CROSS_TENANT: 403,
	OPS_GRANT_INVALID: 403,
	OPS_INCIDENT_NOT_FOUND: 404,
	OPS_INCIDENT_STATUS_INVALID: 409,
	OPS_INCIDENT_RUNBOOK_REQUIRED: 409,
	OPS_HEALTH_CHECK_NOT_FOUND: 404,
	OPS_STALE_CHECKED_AT: 409,
	OPS_REVISION_CONFLICT: 409,
};
export type OperationsErrorCode =
	(typeof OPERATIONS_ERROR_CODES)[keyof typeof OPERATIONS_ERROR_CODES];
export function resolveOperationsErrorStatus(
	code: OperationsErrorCode,
): number {
	return OPERATIONS_ERROR_STATUS_MAP[
		code as keyof typeof OPERATIONS_ERROR_STATUS_MAP
	];
}
