import { z } from "zod";
export const SIMULATION_ERROR_CODES = {
	DUPLICATE_IDEMPOTENCY: "SIM_DUPLICATE_IDEMPOTENCY",
	CROSS_TENANT: "SIM_CROSS_TENANT",
	GRANT_INVALID: "SIM_GRANT_INVALID",
	RUN_NOT_FOUND: "SIM_RUN_NOT_FOUND",
	SNAPSHOT_NOT_FOUND: "SIM_SNAPSHOT_NOT_FOUND",
	RUN_ALREADY_FINALIZED: "SIM_RUN_ALREADY_FINALIZED",
	RUN_INVALID_STATUS: "SIM_RUN_INVALID_STATUS",
	DATASET_HASH_MISMATCH: "SIM_DATASET_HASH_MISMATCH",
	CONCURRENT_MUTATION: "SIM_CONCURRENT_MUTATION",
};
export const simulationErrorCodeSchema = z.enum(
	Object.values(SIMULATION_ERROR_CODES) as [string, ...string[]],
);
export const SIMULATION_ERROR_STATUS_MAP = {
	SIM_DUPLICATE_IDEMPOTENCY: 409,
	SIM_CROSS_TENANT: 403,
	SIM_GRANT_INVALID: 403,
	SIM_RUN_NOT_FOUND: 404,
	SIM_SNAPSHOT_NOT_FOUND: 404,
	SIM_RUN_ALREADY_FINALIZED: 409,
	SIM_RUN_INVALID_STATUS: 422,
	SIM_DATASET_HASH_MISMATCH: 422,
	SIM_CONCURRENT_MUTATION: 409,
};
export type SimulationErrorCode =
	(typeof SIMULATION_ERROR_CODES)[keyof typeof SIMULATION_ERROR_CODES];
export function resolveSimulationErrorStatus(
	code: SimulationErrorCode,
): number {
	return SIMULATION_ERROR_STATUS_MAP[
		code as keyof typeof SIMULATION_ERROR_STATUS_MAP
	];
}
