import { z } from "zod";
export const CAPITAL_ERROR_CODES = {
	SCOPE_DENIED: "CAP_SCOPE_DENIED",
	ACCOUNT_NOT_FOUND: "CAP_ACCOUNT_NOT_FOUND",
	ALLOCATION_NOT_FOUND: "CAP_ALLOCATION_NOT_FOUND",
	RESERVATION_NOT_FOUND: "CAP_RESERVATION_NOT_FOUND",
	INSUFFICIENT_AVAILABLE: "CAP_INSUFFICIENT_AVAILABLE",
	GRANT_INVALID: "CAP_GRANT_INVALID",
	CROSS_TENANT: "CAP_CROSS_TENANT",
	DOUBLE_RESERVATION: "CAP_DOUBLE_RESERVATION",
	REAL_MODE_REJECTED: "CAP_REAL_MODE_REJECTED",
	REVISION_CONFLICT: "CAP_REVISION_CONFLICT",
	RELEASE_EXCEEDS_RESERVED: "CAP_RELEASE_EXCEEDS_RESERVED",
	INVALID_RESERVATION_STATE: "CAP_INVALID_RESERVATION_STATE",
};
export const capitalErrorCodeSchema = z.enum(
	Object.values(CAPITAL_ERROR_CODES) as [string, ...string[]],
);
export const CAPITAL_ERROR_STATUS_MAP = {
	CAP_SCOPE_DENIED: 403,
	CAP_ACCOUNT_NOT_FOUND: 404,
	CAP_ALLOCATION_NOT_FOUND: 404,
	CAP_RESERVATION_NOT_FOUND: 404,
	CAP_INSUFFICIENT_AVAILABLE: 409,
	CAP_GRANT_INVALID: 403,
	CAP_CROSS_TENANT: 403,
	CAP_DOUBLE_RESERVATION: 409,
	CAP_REAL_MODE_REJECTED: 422,
	CAP_REVISION_CONFLICT: 409,
	CAP_RELEASE_EXCEEDS_RESERVED: 409,
	CAP_INVALID_RESERVATION_STATE: 409,
};
export type CapitalErrorCode =
	(typeof CAPITAL_ERROR_CODES)[keyof typeof CAPITAL_ERROR_CODES];
export function resolveCapitalErrorStatus(code: CapitalErrorCode): number {
	return CAPITAL_ERROR_STATUS_MAP[
		code as keyof typeof CAPITAL_ERROR_STATUS_MAP
	];
}
