import {
	CAPABILITY_MANIFEST_CATALOG_VERSION,
	type CapabilityManifestCatalog,
	type CapabilityManifestEntry,
} from "./schema";

const P02_FOUNDATION_MODES = ["SIMULATED"] as const;

const defaultAuditPolicy = {
	requiresCorrelationId: true,
	requiresActorPrincipalId: true,
	requiresChannel: true,
};

const defaultApiTimeout = {
	apiSeconds: 30,
};

const governanceKernelTimeout = {
	apiSeconds: 30,
	governancePortSeconds: 2,
};

function entry(partial: CapabilityManifestEntry): CapabilityManifestEntry {
	return partial;
}

export const CAPABILITY_MANIFEST_V1_ENTRIES: CapabilityManifestEntry[] = [
	entry({
		capabilityId: "identity.principal.register",
		version: 1,
		ownerModule: "identity",
		inputSchemaRef: "registerPrincipalCommandSchema",
		outputSchemaRef: "identityCommandResultSchema",
		errorSchemaRef: "identityErrorDetailsSchema",
		requiredGrants: ["identity.admin"],
		allowedChannels: ["ui", "sdk"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "REVERSIBLE",
		idempotencyPolicy: { key: "commandId", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/owner/onboarding/register",
			api: "/v1/identity/principals",
			tool: "identity.principal.register",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "identity.session.revoke",
		version: 1,
		ownerModule: "identity",
		inputSchemaRef: "recordSessionRevokedCommandSchema",
		outputSchemaRef: "identityCommandResultSchema",
		errorSchemaRef: "identityErrorDetailsSchema",
		requiredGrants: ["identity.admin", "identity.self"],
		allowedChannels: ["ui", "sdk"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "REVERSIBLE",
		idempotencyPolicy: { key: "commandId", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/owner/settings/sessions",
			api: "/v1/identity/sessions/revoke",
			tool: "identity.session.revoke",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "identity.principal.get",
		version: 1,
		ownerModule: "identity",
		// Read with no request body: no input contract is defined.
		inputSchemaDeferred: true,
		errorSchemaRef: "identityErrorDetailsSchema",
		requiredGrants: ["identity.read", "identity.self"],
		allowedChannels: ["ui", "sdk"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "READ_ONLY",
		idempotencyPolicy: { key: "none", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/owner/settings/profile",
			api: "/v1/identity/principals/{principalId}",
			tool: "identity.principal.get",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "identity.principal.suspend",
		version: 1,
		ownerModule: "identity",
		inputSchemaRef: "suspendPrincipalCommandSchema",
		outputSchemaRef: "identityCommandResultSchema",
		errorSchemaRef: "identityErrorDetailsSchema",
		requiredGrants: ["identity.admin"],
		allowedChannels: ["ui", "sdk"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "REVERSIBLE",
		idempotencyPolicy: { key: "commandId", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/platform/identity/principals",
			api: "/v1/identity/principals/{principalId}/suspend",
			tool: "identity.principal.suspend",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "identity.principal.revoke",
		version: 1,
		ownerModule: "identity",
		inputSchemaRef: "revokePrincipalCommandSchema",
		outputSchemaRef: "identityCommandResultSchema",
		errorSchemaRef: "identityErrorDetailsSchema",
		requiredGrants: ["identity.admin"],
		allowedChannels: ["ui", "sdk"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		// REVOKED is terminal (D-IDN-025): the effect must not be undone.
		effectClass: "IRREVERSIBLE",
		idempotencyPolicy: { key: "commandId", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/platform/identity/principals",
			api: "/v1/identity/principals/{principalId}/revoke",
			tool: "identity.principal.revoke",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "identity.session.list",
		version: 1,
		ownerModule: "identity",
		// Leitura sem corpo de requisicao: sem contrato de entrada definido.
		inputSchemaDeferred: true,
		errorSchemaRef: "identityErrorDetailsSchema",
		requiredGrants: ["identity.read", "identity.self"],
		allowedChannels: ["ui", "sdk"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "READ_ONLY",
		idempotencyPolicy: { key: "none", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/owner/settings/sessions",
			api: "/v1/identity/principals/{principalId}/sessions",
			tool: "identity.session.list",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "identity.session.list-revoked",
		version: 1,
		ownerModule: "identity",
		// Read with no request body: no input contract is defined.
		inputSchemaDeferred: true,
		errorSchemaRef: "identityErrorDetailsSchema",
		requiredGrants: ["identity.admin"],
		allowedChannels: ["ui", "sdk"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "READ_ONLY",
		idempotencyPolicy: { key: "none", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/platform/identity/sessions",
			api: "/v1/identity/sessions/revoked",
			tool: "identity.session.list-revoked",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "organizations.agency.create",
		version: 1,
		ownerModule: "organizations",
		inputSchemaRef: "createAgencyCommandSchema",
		outputSchemaRef: "commandResultSchema",
		errorSchemaRef: "organizationErrorDetailsSchema",
		requiredGrants: ["owner.session"],
		allowedChannels: ["ui", "sdk"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "REVERSIBLE",
		idempotencyPolicy: { key: "commandId", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/owner/onboarding/agency",
			api: "/v1/organizations/agencies",
			tool: "organizations.agency.create",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "organizations.agency.list",
		version: 1,
		ownerModule: "organizations",
		// Leitura sem corpo: sem contrato de entrada.
		inputSchemaDeferred: true,
		errorSchemaRef: "organizationErrorDetailsSchema",
		requiredGrants: ["owner.session"],
		allowedChannels: ["ui", "sdk"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "READ_ONLY",
		idempotencyPolicy: { key: "none", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/owner/organizations",
			api: "/v1/organizations/agencies",
			tool: "organizations.agency.list",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "organizations.agency.get",
		version: 1,
		ownerModule: "organizations",
		inputSchemaDeferred: true,
		errorSchemaRef: "organizationErrorDetailsSchema",
		// R04: "Membership ativo" — token mais proximo do guard real
		// (requireAgencyMembership); R04 nao nomeia o token.
		requiredGrants: ["organizations.member"],
		allowedChannels: ["ui", "sdk"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "READ_ONLY",
		idempotencyPolicy: { key: "none", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/owner/organizations",
			api: "/v1/organizations/agencies/{agencyId}",
			tool: "organizations.agency.get",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "organizations.membership.list",
		version: 1,
		ownerModule: "organizations",
		inputSchemaDeferred: true,
		errorSchemaRef: "organizationErrorDetailsSchema",
		requiredGrants: ["organizations.member"],
		allowedChannels: ["ui", "sdk"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "READ_ONLY",
		idempotencyPolicy: { key: "none", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/owner/organizations/team",
			api: "/v1/organizations/agencies/{agencyId}/memberships",
			tool: "organizations.membership.list",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "organizations.membership.get",
		version: 1,
		ownerModule: "organizations",
		inputSchemaDeferred: true,
		errorSchemaRef: "organizationErrorDetailsSchema",
		requiredGrants: ["organizations.member"],
		allowedChannels: ["ui", "sdk"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "READ_ONLY",
		idempotencyPolicy: { key: "none", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/owner/organizations/team",
			api: "/v1/organizations/agencies/{agencyId}/memberships/{membershipId}",
			tool: "organizations.membership.get",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "organizations.agency.updateMarkets",
		version: 1,
		ownerModule: "organizations",
		inputSchemaRef: "updateAgencyMarketsCommandSchema",
		outputSchemaRef: "commandResultSchema",
		errorSchemaRef: "organizationErrorDetailsSchema",
		requiredGrants: ["organizations.admin"],
		allowedChannels: ["ui", "sdk"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "REVERSIBLE",
		idempotencyPolicy: { key: "commandId", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/owner/agency/markets",
			api: "/v1/organizations/agencies/{agencyId}/markets",
			tool: "organizations.agency.updateMarkets",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "organizations.membership.invite",
		version: 1,
		ownerModule: "organizations",
		inputSchemaRef: "inviteMemberCommandSchema",
		outputSchemaRef: "commandResultSchema",
		errorSchemaRef: "organizationErrorDetailsSchema",
		requiredGrants: ["organizations.admin", "organizations.owner"],
		allowedChannels: ["ui", "sdk"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "REVERSIBLE",
		idempotencyPolicy: { key: "commandId", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/owner/team/invite",
			api: "/v1/organizations/agencies/{agencyId}/memberships/invite",
			tool: "organizations.membership.invite",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "organizations.membership.activate",
		version: 1,
		ownerModule: "organizations",
		inputSchemaRef: "activateMembershipCommandSchema",
		outputSchemaRef: "commandResultSchema",
		errorSchemaRef: "organizationErrorDetailsSchema",
		requiredGrants: ["organizations.invited"],
		allowedChannels: ["ui", "sdk"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "REVERSIBLE",
		idempotencyPolicy: { key: "commandId", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/owner/team/activate",
			api: "/v1/organizations/agencies/{agencyId}/memberships/{membershipId}/activate",
			tool: "organizations.membership.activate",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "organizations.membership.revoke",
		version: 1,
		ownerModule: "organizations",
		inputSchemaRef: "revokeMembershipCommandSchema",
		outputSchemaRef: "commandResultSchema",
		errorSchemaRef: "organizationErrorDetailsSchema",
		requiredGrants: ["organizations.owner", "organizations.admin"],
		allowedChannels: ["ui", "sdk"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "REVERSIBLE",
		idempotencyPolicy: { key: "commandId", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/owner/team/revoke",
			api: "/v1/organizations/agencies/{agencyId}/memberships/{membershipId}/revoke",
			tool: "organizations.membership.revoke",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "organizations.membership.acceptInvite",
		version: 1,
		ownerModule: "organizations",
		inputSchemaRef: "acceptInviteByTokenCommandSchema",
		outputSchemaRef: "commandResultSchema",
		errorSchemaRef: "organizationErrorDetailsSchema",
		requiredGrants: ["organizations.invite.token"],
		allowedChannels: ["ui"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "REVERSIBLE",
		idempotencyPolicy: { key: "commandId", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/invite/accept",
			api: "/v1/organizations/invites/accept",
			tool: "organizations.membership.acceptInvite",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "governance.grant.issue",
		version: 1,
		ownerModule: "governance",
		inputSchemaRef: "issueGrantCommandSchema",
		outputSchemaRef: "governanceCommandResultSchema",
		errorSchemaRef: "governanceErrorDetailsSchema",
		requiredGrants: ["governance.owner", "governance.delegate"],
		allowedChannels: ["ui", "sdk"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "REVERSIBLE",
		idempotencyPolicy: { key: "commandId", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/owner/governance/grants/issue",
			api: "/v1/governance/grants",
			tool: "governance.grant.issue",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "governance.grant.revoke",
		version: 1,
		ownerModule: "governance",
		inputSchemaRef: "revokeGrantCommandSchema",
		outputSchemaRef: "governanceCommandResultSchema",
		errorSchemaRef: "governanceErrorDetailsSchema",
		requiredGrants: ["governance.owner", "governance.issuer"],
		allowedChannels: ["ui", "sdk"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "REVERSIBLE",
		idempotencyPolicy: { key: "commandId", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/owner/governance/grants/revoke",
			api: "/v1/governance/grants/revoke",
			tool: "governance.grant.revoke",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "governance.delegation.create",
		version: 1,
		ownerModule: "governance",
		inputSchemaRef: "createDelegationCommandSchema",
		outputSchemaRef: "governanceCommandResultSchema",
		errorSchemaRef: "governanceErrorDetailsSchema",
		requiredGrants: ["governance.parent_grant"],
		allowedChannels: ["ui", "sdk"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "REVERSIBLE",
		idempotencyPolicy: { key: "commandId", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/owner/governance/delegations/create",
			api: "/v1/governance/delegations",
			tool: "governance.delegation.create",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "governance.changeProposal.submit",
		version: 1,
		ownerModule: "governance",
		inputSchemaRef: "submitChangeProposalCommandSchema",
		outputSchemaRef: "governanceCommandResultSchema",
		errorSchemaRef: "governanceErrorDetailsSchema",
		requiredGrants: ["governance.operator"],
		allowedChannels: ["ui", "sdk", "worker"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "REVERSIBLE",
		idempotencyPolicy: { key: "commandId", duplicateBehavior: "replay" },
		approvalPolicy: {
			kind: "policy_by_kind",
			notes: "INSTITUTIONAL/HIERARCHY_MODE require Owner G7",
		},
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/owner/governance/proposals/submit",
			api: "/v1/governance/change-proposals",
			tool: "governance.changeProposal.submit",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "governance.approval.resolve",
		version: 1,
		ownerModule: "governance",
		inputSchemaRef: "resolveApprovalCommandSchema",
		outputSchemaRef: "governanceCommandResultSchema",
		errorSchemaRef: "governanceErrorDetailsSchema",
		requiredGrants: ["governance.owner"],
		allowedChannels: ["ui"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "IRREVERSIBLE",
		idempotencyPolicy: { key: "commandId", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "owner_g7" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: defaultApiTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/owner/governance/approvals/resolve",
			api: "/v1/governance/approvals/resolve",
			tool: "governance.approval.resolve",
		},
		envelopeVersion: "0.2.0",
	}),
	entry({
		capabilityId: "authorization.can",
		version: 1,
		ownerModule: "graph",
		inputSchemaRef: "T01_INPUT_SCHEMA",
		outputSchemaRef: "T01_OUTPUT_SCHEMA",
		errorSchemaRef: "governanceErrorDetailsSchema",
		requiredGrants: ["session", "epoch"],
		allowedChannels: ["ui", "sdk", "worker"],
		allowedExecutionModes: [...P02_FOUNDATION_MODES],
		effectClass: "READ_ONLY",
		idempotencyPolicy: { key: "intentHash", duplicateBehavior: "replay" },
		approvalPolicy: { kind: "none" },
		budgetPolicy: { kind: "defer" },
		timeoutPolicy: governanceKernelTimeout,
		auditPolicy: defaultAuditPolicy,
		surfaces: {
			ui: "/owner/governance/authority-check",
			api: "/v1/graph/traversals/T01",
			tool: "authorization.can",
		},
		envelopeVersion: "0.2.0",
	}),
];

export const CAPABILITY_MANIFEST_V1_CATALOG: CapabilityManifestCatalog = {
	catalogVersion: CAPABILITY_MANIFEST_CATALOG_VERSION,
	entries: CAPABILITY_MANIFEST_V1_ENTRIES,
};
