import { z } from "zod";
export const DECISIONS_ERROR_CODES = {
	CROSS_TENANT: "DC_CROSS_TENANT",
	AUTHORITY_STALE: "DC_AUTHORITY_STALE",
	INTENT_IMMUTABLE: "DC_INTENT_IMMUTABLE",
	REAL_MODE_REJECTED: "DC_REAL_MODE_REJECTED",
	DECISION_NOT_FOUND: "DC_DECISION_NOT_FOUND",
	AUTHORITY_GRANT_ID_REQUIRED: "DC_AUTHORITY_GRANT_ID_REQUIRED",
	GRANT_ID_MISMATCH: "DC_GRANT_ID_MISMATCH",
	GRANT_NOT_ACTIVE: "DC_GRANT_NOT_ACTIVE",
	AUTHORITY_EPOCH_INSUFFICIENT: "DC_AUTHORITY_EPOCH_INSUFFICIENT",
	GRANT_EPOCH_FUTURE: "DC_GRANT_EPOCH_FUTURE",
} as const;
export type DecisionsErrorCode =
	(typeof DECISIONS_ERROR_CODES)[keyof typeof DECISIONS_ERROR_CODES];
export const decisionsErrorCodeSchema = z.enum(
	Object.values(DECISIONS_ERROR_CODES) as [
		DecisionsErrorCode,
		...DecisionsErrorCode[],
	],
);
export const DECISIONS_ERROR_STATUS_MAP: Record<DecisionsErrorCode, number> = {
	DC_CROSS_TENANT: 403,
	DC_AUTHORITY_STALE: 409,
	DC_INTENT_IMMUTABLE: 409,
	DC_REAL_MODE_REJECTED: 422,
	DC_DECISION_NOT_FOUND: 404,
	DC_AUTHORITY_GRANT_ID_REQUIRED: 400,
	DC_GRANT_ID_MISMATCH: 409,
	DC_GRANT_NOT_ACTIVE: 403,
	DC_AUTHORITY_EPOCH_INSUFFICIENT: 409,
	DC_GRANT_EPOCH_FUTURE: 409,
};
export function resolveDecisionsErrorStatus(code: DecisionsErrorCode): number {
	const status = DECISIONS_ERROR_STATUS_MAP[code];
	if (status === undefined) {
		throw new Error(`Unknown decisions error code: ${code}`);
	}
	return status;
}
