import { z } from "zod";

export const AGENTS_ERROR_CODES = [
	"AGT_AGENT_NOT_FOUND",
	"AGT_VERSION_NOT_FOUND",
	"AGT_SKILL_NOT_FOUND",
	"AGT_SKILL_VERSION_NOT_FOUND",
	"AGT_SKILL_SLUG_CONFLICT",
	"AGT_SKILL_VERSION_NOT_VERIFIED",
	"AGT_SKILL_VERSION_IMMUTABLE",
	"AGT_SKILL_BINDING_EXISTS",
	"AGT_SKILL_EVALUATION_REQUIRED",
	"AGT_SKILL_EVALUATION_GATE_DENIED",
	"AGT_REVISION_CONFLICT",
	"AGT_STATUS_INVALID",
	"AGT_VERSION_IMMUTABLE",
	"AGT_TRAVERSAL_DENIED",
	"AGT_PRINCIPAL_NOT_FOUND",
	"AGT_RUNS_PENDING",
	"AGT_CAPABILITY_UNKNOWN",
	"AGT_IDEMPOTENT_REPLAY",
	"AGT_AUTONOMY_LEVEL_DISABLED",
	"AGT_ROUTINE_NOT_FOUND",
	"AGT_ROUTINE_SLUG_CONFLICT",
	"AGT_ROUTINE_PAUSED",
	"AGT_BUDGET_NOT_FOUND",
	"AGT_BUDGET_EXHAUSTED",
	"AGT_GENERATION_FENCING_MISMATCH",
] as const;

export const agentsErrorCodeSchema = z.enum(AGENTS_ERROR_CODES);

export const AGENTS_ERROR_STATUS_MAP = {
	AGT_AGENT_NOT_FOUND: 404,
	AGT_VERSION_NOT_FOUND: 404,
	AGT_SKILL_NOT_FOUND: 404,
	AGT_SKILL_VERSION_NOT_FOUND: 404,
	AGT_SKILL_SLUG_CONFLICT: 409,
	AGT_SKILL_VERSION_NOT_VERIFIED: 409,
	AGT_SKILL_VERSION_IMMUTABLE: 409,
	AGT_SKILL_BINDING_EXISTS: 409,
	AGT_SKILL_EVALUATION_REQUIRED: 409,
	AGT_SKILL_EVALUATION_GATE_DENIED: 403,
	AGT_REVISION_CONFLICT: 409,
	AGT_STATUS_INVALID: 409,
	AGT_VERSION_IMMUTABLE: 409,
	AGT_TRAVERSAL_DENIED: 403,
	AGT_PRINCIPAL_NOT_FOUND: 404,
	AGT_RUNS_PENDING: 409,
	AGT_CAPABILITY_UNKNOWN: 400,
	AGT_IDEMPOTENT_REPLAY: 200,
	AGT_AUTONOMY_LEVEL_DISABLED: 403,
	AGT_ROUTINE_NOT_FOUND: 404,
	AGT_ROUTINE_SLUG_CONFLICT: 409,
	AGT_ROUTINE_PAUSED: 409,
	AGT_BUDGET_NOT_FOUND: 404,
	AGT_BUDGET_EXHAUSTED: 409,
	AGT_GENERATION_FENCING_MISMATCH: 409,
} as const;

export const agentsErrorDetailsSchema = z.object({
	code: agentsErrorCodeSchema,
	message: z.string().optional(),
});

export type AgentsErrorCode = (typeof AGENTS_ERROR_CODES)[number];
export type AgentsErrorDetails = z.infer<typeof agentsErrorDetailsSchema>;

export function resolveAgentsErrorStatus(code: AgentsErrorCode): number {
	return AGENTS_ERROR_STATUS_MAP[code as keyof typeof AGENTS_ERROR_STATUS_MAP];
}
