import { z } from "zod";
export const PORTFOLIOS_ERROR_CODES = {
	DUPLICATE_POSITION_KEY: "PF_DUPLICATE_POSITION_KEY",
	DUPLICATE_IDEMPOTENCY: "PF_DUPLICATE_IDEMPOTENCY",
	CROSS_TENANT: "PF_CROSS_TENANT",
	REAL_MODE_REJECTED: "PF_REAL_MODE_REJECTED",
	PORTFOLIO_NOT_FOUND: "PF_PORTFOLIO_NOT_FOUND",
	PORTFOLIO_CLOSED: "PF_PORTFOLIO_CLOSED",
	INVALID_PRICE_REF: "PF_INVALID_PRICE_REF",
	VALUATION_STALE: "PF_VALUATION_STALE",
	ALLOCATION_MISMATCH: "PF_ALLOCATION_MISMATCH",
	RECONCILIATION_NOT_OPEN: "PF_RECONCILIATION_NOT_OPEN",
	RECONCILIATION_NOT_FOUND: "PF_RECONCILIATION_NOT_FOUND",
	LEDGER_PORTFOLIO_REQUIRED: "PF_LEDGER_PORTFOLIO_REQUIRED",
};
export const portfoliosErrorCodeSchema = z.enum(
	Object.values(PORTFOLIOS_ERROR_CODES) as [string, ...string[]],
);
export const PORTFOLIOS_ERROR_STATUS_MAP = {
	PF_DUPLICATE_POSITION_KEY: 409,
	PF_DUPLICATE_IDEMPOTENCY: 409,
	PF_CROSS_TENANT: 403,
	PF_REAL_MODE_REJECTED: 422,
	PF_PORTFOLIO_NOT_FOUND: 404,
	PF_PORTFOLIO_CLOSED: 422,
	PF_INVALID_PRICE_REF: 422,
	PF_VALUATION_STALE: 422,
	PF_ALLOCATION_MISMATCH: 422,
	PF_RECONCILIATION_NOT_OPEN: 422,
	PF_RECONCILIATION_NOT_FOUND: 404,
	PF_LEDGER_PORTFOLIO_REQUIRED: 422,
};
export type PortfoliosErrorCode =
	(typeof PORTFOLIOS_ERROR_CODES)[keyof typeof PORTFOLIOS_ERROR_CODES];
export function resolvePortfoliosErrorStatus(
	code: PortfoliosErrorCode,
): number {
	return PORTFOLIOS_ERROR_STATUS_MAP[
		code as keyof typeof PORTFOLIOS_ERROR_STATUS_MAP
	];
}
